"""empty message

Revision ID: ccfee7ce1d6e
Revises: 
Create Date: 2020-12-14 14:23:16.309850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccfee7ce1d6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kursy_studenci')
    op.drop_table('linki')
    op.drop_table('zadania')
    op.alter_column('kursy', 'nazwa',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('kursy', 'nr_gl_prowadzacego',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint(None, 'kursy', ['nr_kursu'])
    op.drop_constraint('kursy_ibfk_1', 'kursy', type_='foreignkey')
    op.create_foreign_key(None, 'kursy', 'prowadzacy', ['nr_gl_prowadzacego'], ['nr_prowadzacego'])
    op.alter_column('prowadzacy', 'imie',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=True)
    op.alter_column('prowadzacy', 'nazwisko',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=True)
    op.create_index(op.f('ix_prowadzacy_imie'), 'prowadzacy', ['imie'], unique=False)
    op.create_index(op.f('ix_prowadzacy_nazwisko'), 'prowadzacy', ['nazwisko'], unique=False)
    op.create_unique_constraint(None, 'prowadzacy', ['nr_prowadzacego'])
    op.alter_column('studenci', 'imie',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=True)
    op.alter_column('studenci', 'nazwisko',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=True)
    op.create_index(op.f('ix_studenci_imie'), 'studenci', ['imie'], unique=False)
    op.create_index(op.f('ix_studenci_nazwisko'), 'studenci', ['nazwisko'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studenci_nazwisko'), table_name='studenci')
    op.drop_index(op.f('ix_studenci_imie'), table_name='studenci')
    op.alter_column('studenci', 'nazwisko',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=False)
    op.alter_column('studenci', 'imie',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=False)
    op.drop_constraint(None, 'prowadzacy', type_='unique')
    op.drop_index(op.f('ix_prowadzacy_nazwisko'), table_name='prowadzacy')
    op.drop_index(op.f('ix_prowadzacy_imie'), table_name='prowadzacy')
    op.alter_column('prowadzacy', 'nazwisko',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=False)
    op.alter_column('prowadzacy', 'imie',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=False)
    op.drop_constraint(None, 'kursy', type_='foreignkey')
    op.create_foreign_key('kursy_ibfk_1', 'kursy', 'prowadzacy', ['nr_gl_prowadzacego'], ['nr_prowadzacego'], ondelete='CASCADE')
    op.drop_constraint(None, 'kursy', type_='unique')
    op.alter_column('kursy', 'nr_gl_prowadzacego',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('kursy', 'nazwa',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.create_table('zadania',
    sa.Column('nr_zadania', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nr_kursu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('termin', sa.DATE(), nullable=False),
    sa.Column('typ', mysql.ENUM('kolokwium', 'projekt', 'raport', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('opis', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.ForeignKeyConstraint(['nr_kursu'], ['kursy.nr_kursu'], name='zadania_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nr_zadania'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('linki',
    sa.Column('nr_linku', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nr_kursu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('linkk', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.ForeignKeyConstraint(['nr_kursu'], ['kursy.nr_kursu'], name='linki_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nr_linku'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('kursy_studenci',
    sa.Column('nr_indeksu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nr_kursu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nr_indeksu'], ['studenci.nr_indeksu'], name='kursy_studenci_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nr_kursu'], ['kursy.nr_kursu'], name='kursy_studenci_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nr_indeksu', 'nr_kursu'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
