defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.dashboard]
        address = ":8080"
        [entryPoints.dashboard.auth]
            [entryPoints.dashboard.auth.basic]
                users = ["admin:$apr1$HnCa8cdI$xzFWa.XGiBOwlC10VzTvg1"]
    [entryPoints.http]
        address = ":80"
            [entryPoints.http.redirect]
                entryPoint = "https"
    [entryPoints.https]
        address = ":443"
            [entryPoints.https.tls]

[api]
entryPoint="dashboard"

[docker]
domain = "bui2020.site"
watch = true
network = "web"
