apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  ports:
  - name: http
    targetPort: 80
    port: 8080
  selector:
    app: php
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
        tier: frontend
    spec:
      containers:
      - name: php
        image: php-docker
        imagePullPolicy: Never
        ports:
        - containerPort: 80
