apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  labels:
    name: jaeger-operator
spec:
  type: LoadBalancer
  ports:
  - port: 16686
    protocol: TCP
  selector:
    app: jaeger-operator
