apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    name: python
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: fatusia/bui2020:python
          imagePullPolicy: Always
          ports:
            - name: frontend-port
              containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: python
