insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (1, 'Cyclopeltis semicordata (Sw.) J. Sm.', 29);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (2, 'Arabis suffrutescens S. Watson', 43);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (3, 'Eriogonum scopulorum Reveal', 15);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (4, 'Funastrum clausum (Jacq.) Schltr.', 27);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (5, 'Micarea hedlundii Coppins', 21);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (6, 'Eucharis Planch. & Linden', 39);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (7, 'Ternstroemia subsessilis (Britton) Kobuski', 19);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (8, 'Digitaria ischaemum (Schreb.) Schreb. ex Muhl.', 27);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (9, 'Dianthus caryophyllus L.', 28);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (10, 'Acarospora asperata H. Magn.', 39);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (11, 'Symphyotrichum phlogifolium (Muhl. ex Willd.) G.L. Nesom', 30);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (12, 'Dactylorhiza aristata (Fisch. ex Lindl.) Soó var. aristata', 35);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (13, 'Sphaeromeria diversifolia (D.C. Eaton) Rydb.', 28);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (14, 'Eucalyptus siderophloia Benth.', 40);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (15, 'Malacothrix torreyi A. Gray', 20);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (16, 'Linanthus Benth.', 12);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (17, 'Phlox speciosa Pursh ssp. lignosa Brand', 35);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (18, 'Cinclidium Sw.', 4);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (19, 'Polygala penaea L.', 43);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (20, 'Pedicularis bracteosa Benth. var. paysoniana (Pennell) Cronquist', 33);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (21, 'Chenopodium capitatum (L.) Asch.', 8);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (22, 'Solanum clokeyi Munz', 11);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (23, 'Chamaesyce angusta (Engelm.) Small', 6);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (24, 'Nototrichium divaricatum D.H. Lorence', 18);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (25, 'Eugenia eucalyptoides F. Muell.', 7);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (26, 'Sicyos angulatus L.', 27);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (27, 'Hackelia californica (A. Gray) I.M. Johnst.', 4);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (28, 'Pectis rusbyi Greene ex A. Gray', 41);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (29, 'Castilleja raupii Pennell', 25);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (30, 'Sedum valens Björk', 43);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (31, 'Gaillardia arizonica A. Gray', 25);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (32, 'Loxospora elatina (Ach.) A. Massal.', 31);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (33, 'Erigeron strigosus Muhl. ex Willd. var. calcicola J. Allison', 34);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (34, 'Argentina egedii (Wormsk.) Rydb. ssp. groenlandica (Tratt.) Á. Löve', 34);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (35, 'Geum triflorum Pursh var. canescens (Greene) Kartesz & Gandhi', 41);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (36, 'Platygyrium Schimp.', 12);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (37, 'Polycoccum Sauter ex Krober', 39);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (38, 'Erigeron petrophilus Greene var. petrophilus', 38);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (39, 'Athyrium filix-femina (L.) Roth', 1);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (40, 'Minuartia obtusiloba (Rydb.) House', 37);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (41, 'Stylocline psilocarphoides M. Peck', 37);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (42, 'Achnatherum pinetorum (M.E. Jones) Barkworth', 28);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (43, 'Helocarpon crassipes Th. Fr.', 40);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (44, 'Cladonia ecmocyna Leight.', 4);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (45, 'Pinus gerardiana Wall. ex D. Don', 32);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (46, 'Arenaria hookeri Nutt. ssp. desertorum (Maguire) W.A. Weber', 10);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (47, 'Thelypodium integrifolium (Nutt.) Endl. ex Walp.', 1);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (48, 'Acacia macracantha Humb. & Bonpl. ex Willd.', 30);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (49, 'Pteridium aquilinum (L.) Kuhn var. pseudocaudatum (Clute) A. Heller', 37);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (50, 'Silene virginica L.', 16);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (51, 'Candelariella canadensis H. Magn.', 28);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (52, 'Pterygoneurum californicum H.A. Crum', 6);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (53, 'Urochloa plantaginea (Link) R. Webster', 21);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (54, 'Microseris bigelovii (A. Gray) Sch. Bip.', 43);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (55, 'Calochortus amabilis Purdy', 37);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (56, 'Aristida basiramea Engelm. ex Vasey', 8);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (57, 'Rubus hancinianus L.H. Bailey', 20);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (58, 'Yucca angustissima Engelm. ex Trel. var. angustissima', 38);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (59, 'Saxifraga micranthidifolia (Haw.) Steud.', 42);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (60, 'Caloplaca ferrugineofusca (Vain.) H. Magn.', 13);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (61, 'Orthotrichum bartramii R.S. Williams', 27);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (62, 'Neisosperma Raf.', 14);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (63, 'Schizaea robusta Baker', 36);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (64, 'Arctostaphylos stanfordiana Parry ssp. stanfordiana', 41);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (65, 'Helianthus petiolaris Nutt. ssp. fallax Heiser', 4);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (66, 'Mibora Adans.', 12);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (67, 'Elaphoglossum apodum (Kaulf.) Schott ex J. Sm.', 12);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (68, 'Campanulastrum Small', 38);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (69, 'Zygodon gracilis Wilson', 17);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (70, 'Ocotea moschata (Pav. ex Meisn.) Mez', 28);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (71, 'Pyrenula cruenta (Mont.) Vain.', 9);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (72, 'Eleocharis obtusa (Willd.) Schult.', 37);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (73, 'Lupinus benthamii A. Heller var. opimus C.P. Sm.', 1);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (74, 'Stachys rigida Nutt. ex Benth. var. quercetorum (A. Heller) G. Mulligan & D. Munro', 43);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (75, 'Prunus domestica L.', 12);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (76, 'Eriogonum pharnaceoides Torr. var. pharnaceoides', 16);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (77, 'Calluna vulgaris (L.) Hull', 38);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (78, 'Acmella decumbens (Sm.) R.K. Jansen', 41);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (79, 'Geum ×aurantiacum Fr.', 19);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (80, 'Eriophorum brachyantherum Trautv. & C.A. Mey. var. brachyantherum', 34);
insert into kursy (nr_kursu, nazwa, nr_gl_prowadzacego) values (81, 'Eriogonum umbellatum Torr. var. cladophorum Gandog.', 38);
